name: Build Custom Snake

on:
  schedule:
    - cron: "0 0 * * *"   # her gece
  workflow_dispatch:       # elle çalıştırma

permissions:
  contents: write          # output branch'a yazabilsin

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Generate SVG
        run: |
          node --version
          node scripts/generate-snake.mjs

      - name: Publish to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
